title: Tanishka Kohli
description: Portfolio
username: Tanishka Kohli
user_description: >-
  I am a Student, Coder, An aspiring Ethical Hacker, Blockchain and Machine Learning enthusiast.
user_title: Software Developer
email: tanishka.kohli00@gmail,com
twitter_username: kohli00
github_username: tkohli
gplus_username: #
google-analytics:
  id: ''
exclude:
  - package.json
  - src
  - node_modules
baseurl: ''
url: ''
